version: '3.7'
services:
    webserver:
        image: foboyle/airflow-etl:latest
        restart: always
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__CORE__FERNET_KEY='5khjrdIFKBxsWQDGF8FI2u80rs_lA0bsheu2gJTwWGk='
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - /home/ubuntu/airflow/dags:/usr/local/airflow/dags
            - /home/ubuntu/airflow/plugins:/usr/local/airflow/plugins
            - /home/ubuntu/airflow/scripts:/usr/local/airflow/scripts
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3


